# Generated by Django 3.0.2 on 2020-01-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200130_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('surname', models.CharField(max_length=36)),
                ('books', models.ManyToManyField(to='api.Book')),
            ],
        ),
    ]
